name: Format and Update Projects

on:
  push:
    branches:
      - main

jobs:
  format-and-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: pnpm install

      - name: Update Projects
        run: pnpm run update-list

      - name: Format
        run: pnpm run format

      - name: Add, Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format and Update Projects"
